url: "https://imaginginpsychiatry.github.io"
baseurl: "/symposium/"

# Site settings
title: Symposium
email: your-email@domain.com
description: "Imaging in Psychiatry on January 31, 2020. This symposium aims to bring together several experts in the field of psychiatric imaging and discuss the state-of-the-art in this area. In particular, the challenges and barriers for the clinical use of medical imaging in psychiatry will be addressed in the light of the future direction of this interesting field."
keywords: imaging,psychiatry,januari,31,2020,symposium,event,neurology,Kempenheaghe
    
#"Symposium - Imaging in Psychiatry on January 31, 2020"


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210


# Build settings
markdown: kramdown
permalink: pretty
